// Fallback embedded data for Store Analytics Console
export const EMBEDDED_DATA = [
  {
    "POS Order ID": "INV_2627_FRIDO_0012_1971",
    "Order Type": "ONLINE",
    "Product Name": "Frido Cloud Backrest Cushion",
    "Variant Name": "Black",
    "Size": "",
    "Customer Email": "7405626691@frido.in",
    "Customer Phone": "7410000000",
    "Customer Name": "GAURAV JAIN",
    "New Customer": "No",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Frido Experience Store Gachibowli",
    "Employee ID": "EMP_0041",
    "Employee Name": "Gachibowli Store",
    "Return Reason": "",
    "Item Code": "d4f95e5d-f207-4466-9b12-62755f8e2df2",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "PERCENTAGE",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 1999,
    "Amount Paid": 1899,
    "Return Amount": 0,
    "Total Coupon Amount": 100,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 0,
    "_h": 11,
    "_m": 0
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0002_3678",
    "Order Type": "ONLINE",
    "Product Name": "Frido Men's Cloud Comfort Sandal",
    "Variant Name": "Black / 6 UK (40 EU)",
    "Size": "6 UK (40 EU)",
    "Customer Email": "9923248383@frido.in",
    "Customer Phone": "920000000000",
    "Customer Name": "SANKET PATHARE",
    "New Customer": "No",
    "Heard About Frido": "YES",
    "Source": "FRIENDS_FAMILY",
    "Store Name": "Amanora Experience Store",
    "Employee ID": "EMP_0008",
    "Employee Name": "Aakash Sontakke",
    "Return Reason": "",
    "Item Code": "1a62c659-1979-455b-a1b4-c8ba24641264",
    "Payment Modes": "QR_PAYMENT",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "EOSS10",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 2399,
    "Amount Paid": 2159,
    "Return Amount": 0,
    "Total Coupon Amount": 240,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 1,
    "_h": 13,
    "_m": 17
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0002_3677",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Men's Puneri Arch Comfort Sandal",
    "Variant Name": "Classic Black / UK9 (EU43)",
    "Size": "UK9 (EU43)",
    "Customer Email": "9923248383@frido.in",
    "Customer Phone": "920000000000",
    "Customer Name": "SANKET PATHARE",
    "New Customer": "Yes",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Amanora Experience Store",
    "Employee ID": "EMP_0008",
    "Employee Name": "Aakash Sontakke",
    "Return Reason": "",
    "Item Code": "",
    "Payment Modes": "QR_PAYMENT",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "EOSS10",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 2499,
    "Amount Paid": 2249,
    "Return Amount": 0,
    "Total Coupon Amount": 250,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 3,
    "_h": 18,
    "_m": 34
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0018_1129",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Women's Cloud Comfort Sandal",
    "Variant Name": "Black / 7 UK (40 EU)",
    "Size": "7 UK (40 EU)",
    "Customer Email": "7230955777@frido.in",
    "Customer Phone": "917000000000",
    "Customer Name": "KESBI .",
    "New Customer": "Yes",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Golf Course Road",
    "Employee ID": "EMP_0064",
    "Employee Name": "Mayank Kumar",
    "Return Reason": "",
    "Item Code": "RTDMHN-2627N412211",
    "Payment Modes": "RAZORPAY",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 1899,
    "Amount Paid": 1899,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 0,
    "_h": 14,
    "_m": 51
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0006_2991",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Active Knee Cap Support",
    "Variant Name": "M / Blue",
    "Size": "M",
    "Customer Email": "anujver23@gmail.com",
    "Customer Phone": "8240000000",
    "Customer Name": "Anuj Verma",
    "New Customer": "No",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Nexus Westend, Aundh",
    "Employee ID": "EMP_0023",
    "Employee Name": "Nexus Westend, Aundh",
    "Return Reason": "",
    "Item Code": "RTDMHN-2627N287829",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 899,
    "Amount Paid": 899,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 1,
    "_h": 17,
    "_m": 8
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0006_2991",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Nasal Strips",
    "Variant Name": "Pack of 15",
    "Size": "",
    "Customer Email": "anujver23@gmail.com",
    "Customer Phone": "8240000000",
    "Customer Name": "Anuj Verma",
    "New Customer": "No",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Nexus Westend, Aundh",
    "Employee ID": "EMP_0023",
    "Employee Name": "Nexus Westend, Aundh",
    "Return Reason": "",
    "Item Code": "RTDMHN-2627N272152",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 499,
    "Amount Paid": 499,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 2,
    "_h": 12,
    "_m": 25
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0002_3676",
    "Order Type": "ONLINE",
    "Product Name": "FREE GIFT COUPON - â‚¹1000",
    "Variant Name": "Default Title",
    "Size": "",
    "Customer Email": "9426511787@frido.in",
    "Customer Phone": "919000000000",
    "Customer Name": "KARAN TAILOR",
    "New Customer": "No",
    "Heard About Frido": "YES",
    "Source": "FRIENDS_FAMILY",
    "Store Name": "Amanora Experience Store",
    "Employee ID": "EMP_0008",
    "Employee Name": "Aakash Sontakke",
    "Return Reason": "",
    "Item Code": "aff6a8a2-0cb5-43a9-98bb-301c17e143ed",
    "Payment Modes": "QR_PAYMENT",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "EOSS10",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 0,
    "Amount Paid": 0,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 5,
    "_h": 17,
    "_m": 42
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0002_3676",
    "Order Type": "ONLINE",
    "Product Name": "Frido Ergoluxe Electric Standing Desk",
    "Variant Name": "1500mm x 700mm(~5ft x 2.3ft) / All Black",
    "Size": "1500mm x 700mm(~5ft x 2.3ft)",
    "Customer Email": "9426511787@frido.in",
    "Customer Phone": "919000000000",
    "Customer Name": "KARAN TAILOR",
    "New Customer": "No",
    "Heard About Frido": "YES",
    "Source": "FRIENDS_FAMILY",
    "Store Name": "Amanora Experience Store",
    "Employee ID": "EMP_0008",
    "Employee Name": "Aakash Sontakke",
    "Return Reason": "",
    "Item Code": "eb8389c4-8a6b-4caa-87f2-04c4e1460405",
    "Payment Modes": "QR_PAYMENT",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "EOSS10",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 39999,
    "Amount Paid": 35999,
    "Return Amount": 0,
    "Total Coupon Amount": 4000,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 10,
    "_h": 12,
    "_m": 59
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0008_2138",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Orthotics Posture Corrector",
    "Variant Name": "L",
    "Size": "L",
    "Customer Email": "shwetanshu.mehta@gmail.com",
    "Customer Phone": "8800000000",
    "Customer Name": "Shwetanshu Mehta",
    "New Customer": "No",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Kopa Mall",
    "Employee ID": "EMP_0028",
    "Employee Name": "shubham gupta",
    "Return Reason": "",
    "Item Code": "RTDMHN-2627N186938",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 899,
    "Amount Paid": 899,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 0,
    "_h": 18,
    "_m": 16
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0001_2968",
    "Order Type": "ONLINE",
    "Product Name": "Frido Arch Support Insoles",
    "Variant Name": "Large (9-11 UK)",
    "Size": "Large (9-11 UK)",
    "Customer Email": "rajeshrkukreja@gmail.com",
    "Customer Phone": "9890000000",
    "Customer Name": "Rajesh Kukreja",
    "New Customer": "No",
    "Heard About Frido": "YES",
    "Source": "FRIENDS_FAMILY",
    "Store Name": "Phoenix Marketcity Vimannagar",
    "Employee ID": "EMP_0003",
    "Employee Name": "Phoenix Marketcity Vimannagar",
    "Return Reason": "",
    "Item Code": "e9182781-a2f3-4c8f-8e73-534d5b6a8520",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 1199,
    "Amount Paid": 1199,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 1,
    "_h": 20,
    "_m": 33
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0020_1069",
    "Order Type": "ONLINE",
    "Product Name": "Frido Men's Comfort Dual Strap Sandals",
    "Variant Name": "Cloudy Grey / 7 UK (EUR 41)",
    "Size": "7 UK (EUR 41)",
    "Customer Email": "satyanpardhan20@gmail.com",
    "Customer Phone": "8900000000",
    "Customer Name": "Poabhuranjan .",
    "New Customer": "No",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "PMC Whitefield",
    "Employee ID": "EMP_0031",
    "Employee Name": "Sharath Kumar",
    "Return Reason": "",
    "Item Code": "6ed352e9-507f-47b6-a77d-3e4c8151a9ff",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "IST-AKSH15",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 2499,
    "Amount Paid": 2124,
    "Return Amount": 0,
    "Total Coupon Amount": 375,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 0,
    "_h": 16,
    "_m": 50
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0016_1198",
    "Order Type": "ONLINE",
    "Product Name": "Frido Ultimate Neck Contour Cervical Plus Pillow",
    "Variant Name": "Premium Blue",
    "Size": "",
    "Customer Email": "7064079550@frido.in",
    "Customer Phone": "917000000000",
    "Customer Name": "AAHANA A",
    "New Customer": "No",
    "Heard About Frido": "YES",
    "Source": "INSTAGRAM",
    "Store Name": "Lulu Mall",
    "Employee ID": "EMP_0057",
    "Employee Name": "Trishul K",
    "Return Reason": "",
    "Item Code": "12ab6e2d-cab8-4e9c-9005-6bfb310f2a3c",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 1699,
    "Amount Paid": 1699,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 1,
    "_h": 19,
    "_m": 7
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0002_3675",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Premium Car Wedge Seat Cushion",
    "Variant Name": "Midnight Black",
    "Size": "",
    "Customer Email": "8237267557@frido.in",
    "Customer Phone": "918000000000",
    "Customer Name": "AKSHAY PACHARNE",
    "New Customer": "Yes",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Amanora Experience Store",
    "Employee ID": "EMP_0008",
    "Employee Name": "Aakash Sontakke",
    "Return Reason": "",
    "Item Code": "",
    "Payment Modes": "QR_PAYMENT",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "EOSS10",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 1799,
    "Amount Paid": 1619,
    "Return Amount": 0,
    "Total Coupon Amount": 180,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 15,
    "_h": 11,
    "_m": 24
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0015_1329",
    "Order Type": "ONLINE",
    "Product Name": "Frido Women's Arch Comfort Sandals",
    "Variant Name": "Light Gold / 8 UK (41 EU)",
    "Size": "8 UK (41 EU)",
    "Customer Email": "9108954704@frido.in",
    "Customer Phone": "9110000000",
    "Customer Name": "SHANMATHI .",
    "New Customer": "No",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Bhartiya Mall Store",
    "Employee ID": "EMP_0049",
    "Employee Name": "Mazhar Hussain",
    "Return Reason": "",
    "Item Code": "6711e01e-8692-4491-9b5a-e00a58566a87",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "500_Voucher",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 2199,
    "Amount Paid": 1699,
    "Return Amount": 0,
    "Total Coupon Amount": 500,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 0,
    "_h": 12,
    "_m": 41
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0012_1969",
    "Order Type": "ONLINE",
    "Product Name": "Frido Ultimate Lap Desk Pillow",
    "Variant Name": "Grey",
    "Size": "",
    "Customer Email": "pattabhi.vemulapati@gmail.com",
    "Customer Phone": "8010000000",
    "Customer Name": "PATTABHI VEMULAPATI",
    "New Customer": "No",
    "Heard About Frido": "YES",
    "Source": "GOOGLE_SEARCH",
    "Store Name": "Frido Experience Store Gachibowli",
    "Employee ID": "EMP_0041",
    "Employee Name": "Gachibowli Store",
    "Return Reason": "",
    "Item Code": "9e243285-cb97-40b9-b4c6-962db051ab7c",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "500_Voucher",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 3299,
    "Amount Paid": 2799,
    "Return Amount": 0,
    "Total Coupon Amount": 500,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 2,
    "_h": 20,
    "_m": 58
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0006_2989",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Men's Comfort Dual Strap Sandals",
    "Variant Name": "Olive Green / 9 UK (EUR 43)",
    "Size": "9 UK (EUR 43)",
    "Customer Email": "jyotikiswe01@gmail.com",
    "Customer Phone": "9000000000",
    "Customer Name": "Jyoti Kiswe",
    "New Customer": "No",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Nexus Westend, Aundh",
    "Employee ID": "EMP_0023",
    "Employee Name": "Nexus Westend, Aundh",
    "Return Reason": "",
    "Item Code": "RTDMHN-2627N576301",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "PERCENTAGE",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 2499,
    "Amount Paid": 2374,
    "Return Amount": 0,
    "Total Coupon Amount": 125,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 7,
    "_h": 19,
    "_m": 15
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0015_1328",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Cuddle Sleep Pillow",
    "Variant Name": "Mocha Brown",
    "Size": "",
    "Customer Email": "9108954704@frido.in",
    "Customer Phone": "919000000000",
    "Customer Name": "SHANMATHI .",
    "New Customer": "No",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Bhartiya Mall Store",
    "Employee ID": "EMP_0049",
    "Employee Name": "Mazhar Hussain",
    "Return Reason": "",
    "Item Code": "91",
    "Payment Modes": "CASH",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "500_Voucher",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 2499,
    "Amount Paid": 1999,
    "Return Amount": 0,
    "Total Coupon Amount": 500,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 4,
    "_h": 19,
    "_m": 32
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0015_1327",
    "Order Type": "ONLINE",
    "Product Name": "Frido 3D Posture Plus Ergonomic Chair",
    "Variant Name": "Royal White",
    "Size": "",
    "Customer Email": "9108954704@frido.in",
    "Customer Phone": "919000000000",
    "Customer Name": "SHANMATHI .",
    "New Customer": "No",
    "Heard About Frido": "NO",
    "Source": "",
    "Store Name": "Bhartiya Mall Store",
    "Employee ID": "EMP_0049",
    "Employee Name": "Mazhar Hussain",
    "Return Reason": "",
    "Item Code": "f73306d5-343c-460f-a006-beea9dca0104",
    "Payment Modes": "CASH",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "FIXED",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 19999,
    "Amount Paid": 17999,
    "Return Amount": 0,
    "Total Coupon Amount": 2000,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 12,
    "_h": 14,
    "_m": 49
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0011_1729",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Men's Cloud Comfort Shoes - Lace Ups",
    "Variant Name": "Black / 8 UK",
    "Size": "8 UK",
    "Customer Email": "9440080160@frido.in",
    "Customer Phone": "9440000000",
    "Customer Name": "srinivas .",
    "New Customer": "No",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Lakeshore Y junction",
    "Employee ID": "EMP_0034",
    "Employee Name": "Store_0008 Login",
    "Return Reason": "",
    "Item Code": "RTDMHN-2627N128361",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "PERCENTAGE",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 2199,
    "Amount Paid": 2023,
    "Return Amount": 0,
    "Total Coupon Amount": 176,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 1,
    "_h": 17,
    "_m": 6
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0017_1171",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Women's Ethnic Comfort Flat Sandal",
    "Variant Name": "Satin Gold / 7 UK (40 EU)",
    "Size": "7 UK (40 EU)",
    "Customer Email": "9211777745@frido.in",
    "Customer Phone": "919000000000",
    "Customer Name": "Sumit Solanki",
    "New Customer": "Yes",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Vegas Mall",
    "Employee ID": "EMP_0065",
    "Employee Name": "Asmit Kumar",
    "Return Reason": "",
    "Item Code": "RTDMHN-2627N264920",
    "Payment Modes": "QR_PAYMENT",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 1899,
    "Amount Paid": 1899,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 0,
    "_h": 13,
    "_m": 23
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0019_1085",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Cold & Hot Therapy Cap",
    "Variant Name": "Aqua Blue",
    "Size": "",
    "Customer Email": "pravesh8499@gmail.com",
    "Customer Phone": "9900000000",
    "Customer Name": "Pravesh Verma",
    "New Customer": "No",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Omaxe Store",
    "Employee ID": "EMP_0069",
    "Employee Name": "Hamid R",
    "Return Reason": "",
    "Item Code": "RTDMHN-2627N379494",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 1599,
    "Amount Paid": 1599,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 1,
    "_h": 15,
    "_m": 40
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0014_1263",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Plantar Fasciitis Pain Relief Ortho Insoles",
    "Variant Name": "S (5-8 UK)",
    "Size": "S (5-8 UK)",
    "Customer Email": "7032307460@frido.in",
    "Customer Phone": "917000000000",
    "Customer Name": "K L REDDY .",
    "New Customer": "Yes",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Kompally Store",
    "Employee ID": "EMP_0047",
    "Employee Name": "Kompally Store",
    "Return Reason": "",
    "Item Code": "RTDMHN-2627N287166",
    "Payment Modes": "CASH",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 1499,
    "Amount Paid": 1499,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 0,
    "_h": 11,
    "_m": 57
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0014_1263",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Orthotics Heel Protector",
    "Variant Name": "Black / L",
    "Size": "L",
    "Customer Email": "7032307460@frido.in",
    "Customer Phone": "917000000000",
    "Customer Name": "K L REDDY .",
    "New Customer": "Yes",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Kompally Store",
    "Employee ID": "EMP_0047",
    "Employee Name": "Kompally Store",
    "Return Reason": "",
    "Item Code": "RTDMHN-2627N528740",
    "Payment Modes": "CASH",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 899,
    "Amount Paid": 899,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 2,
    "_h": 20,
    "_m": 14
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0011_1728",
    "Order Type": "ONLINE",
    "Product Name": "Frido Men's Puneri Arch Comfort Sandal",
    "Variant Name": "Classic Black / UK8 (EU42)",
    "Size": "UK8 (EU42)",
    "Customer Email": "9440080160@frido.in",
    "Customer Phone": "9440000000",
    "Customer Name": "srinivas .",
    "New Customer": "No",
    "Heard About Frido": "YES",
    "Source": "GOOGLE_SEARCH",
    "Store Name": "Lakeshore Y junction",
    "Employee ID": "EMP_0034",
    "Employee Name": "Store_0008 Login",
    "Return Reason": "",
    "Item Code": "e6dd0d9d-2f56-49f6-8eb3-8e3204e294ed",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "PERCENTAGE",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 2499,
    "Amount Paid": 2299,
    "Return Amount": 0,
    "Total Coupon Amount": 200,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 2,
    "_h": 18,
    "_m": 31
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0016_1197",
    "Order Type": "ONLINE",
    "Product Name": "Frido Ultimate Neck Contour Cervical Plus Pillow",
    "Variant Name": "Premium Blue",
    "Size": "",
    "Customer Email": "9632622294@frido.in",
    "Customer Phone": "920000000000",
    "Customer Name": "PARIKSHITH C",
    "New Customer": "No",
    "Heard About Frido": "YES",
    "Source": "INSTAGRAM",
    "Store Name": "Lulu Mall",
    "Employee ID": "EMP_0057",
    "Employee Name": "Trishul K",
    "Return Reason": "",
    "Item Code": "01035795-9aae-408d-9817-c333d0f9a54d",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 1699,
    "Amount Paid": 1699,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 3,
    "_h": 15,
    "_m": 48
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0016_1197",
    "Order Type": "ONLINE",
    "Product Name": "Frido Ultimate Car Backrest Cushion",
    "Variant Name": "Premium Black",
    "Size": "",
    "Customer Email": "9632622294@frido.in",
    "Customer Phone": "920000000000",
    "Customer Name": "PARIKSHITH C",
    "New Customer": "No",
    "Heard About Frido": "YES",
    "Source": "INSTAGRAM",
    "Store Name": "Lulu Mall",
    "Employee ID": "EMP_0057",
    "Employee Name": "Trishul K",
    "Return Reason": "",
    "Item Code": "818d8100-51f6-43d8-a73f-f82c68083562",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 1199,
    "Amount Paid": 1199,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 11,
    "_h": 18,
    "_m": 5
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0017_1170",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Orthotics Posture Corrector",
    "Variant Name": "M",
    "Size": "M",
    "Customer Email": "pantsaarthak@gmail.com",
    "Customer Phone": "9600000000",
    "Customer Name": "Saarthak Pant",
    "New Customer": "No",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Vegas Mall",
    "Employee ID": "EMP_0065",
    "Employee Name": "Asmit Kumar",
    "Return Reason": "",
    "Item Code": "RTDMHN-2627N284999",
    "Payment Modes": "QR_PAYMENT",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 899,
    "Amount Paid": 899,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 3,
    "_h": 16,
    "_m": 22
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0008_2137",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Cloud Comfort Slippers",
    "Variant Name": "Olive Green / 9 UK",
    "Size": "9 UK",
    "Customer Email": "7507044559@frido.in",
    "Customer Phone": "918000000000",
    "Customer Name": "Chandrakant Naik",
    "New Customer": "Yes",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Kopa Mall",
    "Employee ID": "EMP_0028",
    "Employee Name": "shubham gupta",
    "Return Reason": "",
    "Item Code": "RTDMHN-2627117448",
    "Payment Modes": "CASH",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 849,
    "Amount Paid": 849,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 3,
    "_h": 15,
    "_m": 39
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0008_2137",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Cloud Comfort Arch Support Slippers",
    "Variant Name": "Charcoal Black / 8 UK",
    "Size": "8 UK",
    "Customer Email": "7507044559@frido.in",
    "Customer Phone": "918000000000",
    "Customer Name": "Chandrakant Naik",
    "New Customer": "Yes",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Kopa Mall",
    "Employee ID": "EMP_0028",
    "Employee Name": "shubham gupta",
    "Return Reason": "",
    "Item Code": "RTDMHN-2627N205834",
    "Payment Modes": "CASH",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 949,
    "Amount Paid": 849,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 100,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 8,
    "_h": 18,
    "_m": 56
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0008_2137",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Cloud Comfort Arch Support Slippers",
    "Variant Name": "Charcoal Black / 10 UK",
    "Size": "10 UK",
    "Customer Email": "7507044559@frido.in",
    "Customer Phone": "918000000000",
    "Customer Name": "Chandrakant Naik",
    "New Customer": "Yes",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Kopa Mall",
    "Employee ID": "EMP_0028",
    "Employee Name": "shubham gupta",
    "Return Reason": "",
    "Item Code": "HJ017654",
    "Payment Modes": "CASH",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 949,
    "Amount Paid": 850,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 99,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 13,
    "_h": 11,
    "_m": 13
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0012_1968",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Active Socks",
    "Variant Name": "M (UK 6-9) / Charcoal Grey",
    "Size": "M (UK 6-9)",
    "Customer Email": "9456939597@frido.in",
    "Customer Phone": "919000000000",
    "Customer Name": "ankit sharma",
    "New Customer": "Yes",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Frido Experience Store Gachibowli",
    "Employee ID": "EMP_0041",
    "Employee Name": "Gachibowli Store",
    "Return Reason": "",
    "Item Code": "RTD1562561",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 399,
    "Amount Paid": 399,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 4,
    "_h": 19,
    "_m": 30
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0017_1169",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Premium Car Back Rest Cushion",
    "Variant Name": "Midnight Black",
    "Size": "",
    "Customer Email": "Solanki.vikas07@gmail.com",
    "Customer Phone": "9560000000",
    "Customer Name": "Vikas solanki",
    "New Customer": "No",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Vegas Mall",
    "Employee ID": "EMP_0062",
    "Employee Name": "Nishant Kumar",
    "Return Reason": "",
    "Item Code": "RTDMHN-2627N243482",
    "Payment Modes": "QR_PAYMENT",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "FIXED",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 1799,
    "Amount Paid": 1521,
    "Return Amount": 0,
    "Total Coupon Amount": 278,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 14,
    "_h": 12,
    "_m": 47
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0017_1169",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Premium Car Wedge Seat Cushion",
    "Variant Name": "Midnight Black",
    "Size": "",
    "Customer Email": "Solanki.vikas07@gmail.com",
    "Customer Phone": "9560000000",
    "Customer Name": "Vikas solanki",
    "New Customer": "No",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Vegas Mall",
    "Employee ID": "EMP_0062",
    "Employee Name": "Nishant Kumar",
    "Return Reason": "",
    "Item Code": "RTDMHN-2627N278317",
    "Payment Modes": "QR_PAYMENT",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "FIXED",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 1799,
    "Amount Paid": 1521,
    "Return Amount": 0,
    "Total Coupon Amount": 278,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 19,
    "_h": 13,
    "_m": 4
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0017_1169",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Premium Car Neck Rest Cushion",
    "Variant Name": "Midnight Black",
    "Size": "",
    "Customer Email": "Solanki.vikas07@gmail.com",
    "Customer Phone": "9560000000",
    "Customer Name": "Vikas solanki",
    "New Customer": "No",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Vegas Mall",
    "Employee ID": "EMP_0062",
    "Employee Name": "Nishant Kumar",
    "Return Reason": "",
    "Item Code": "",
    "Payment Modes": "QR_PAYMENT",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "FIXED",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 1499,
    "Amount Paid": 1267,
    "Return Amount": 0,
    "Total Coupon Amount": 232,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 24,
    "_h": 18,
    "_m": 21
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0017_1169",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Cervical Butterfly Pillow",
    "Variant Name": "Blue",
    "Size": "",
    "Customer Email": "Solanki.vikas07@gmail.com",
    "Customer Phone": "9560000000",
    "Customer Name": "Vikas solanki",
    "New Customer": "No",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Vegas Mall",
    "Employee ID": "EMP_0062",
    "Employee Name": "Nishant Kumar",
    "Return Reason": "",
    "Item Code": "RTDMHN-2627N486161",
    "Payment Modes": "QR_PAYMENT",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "FIXED",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 1999,
    "Amount Paid": 1689,
    "Return Amount": 0,
    "Total Coupon Amount": 310,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 29,
    "_h": 19,
    "_m": 38
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0014_1262",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Premium Car Neck Rest Cushion",
    "Variant Name": "Sahara Luxe Tan",
    "Size": "",
    "Customer Email": "9848061761@frido.in",
    "Customer Phone": "920000000000",
    "Customer Name": "MA Rahim",
    "New Customer": "Yes",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Kompally Store",
    "Employee ID": "EMP_0047",
    "Employee Name": "Kompally Store",
    "Return Reason": "",
    "Item Code": "51",
    "Payment Modes": "CASH",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 1499,
    "Amount Paid": 1499,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 16,
    "_h": 17,
    "_m": 55
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0014_1262",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Premium Car Neck Rest Cushion",
    "Variant Name": "Sahara Luxe Tan",
    "Size": "",
    "Customer Email": "9848061761@frido.in",
    "Customer Phone": "920000000000",
    "Customer Name": "MA Rahim",
    "New Customer": "Yes",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Kompally Store",
    "Employee ID": "EMP_0047",
    "Employee Name": "Kompally Store",
    "Return Reason": "",
    "Item Code": "57",
    "Payment Modes": "CASH",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 1499,
    "Amount Paid": 1499,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 21,
    "_h": 12,
    "_m": 12
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0011_1726",
    "Order Type": "ONLINE",
    "Product Name": "Frido Travel Neck Pillow",
    "Variant Name": "Core Black",
    "Size": "",
    "Customer Email": "9849093892@frido.in",
    "Customer Phone": "920000000000",
    "Customer Name": "rushender .",
    "New Customer": "No",
    "Heard About Frido": "YES",
    "Source": "GOOGLE_SEARCH",
    "Store Name": "Lakeshore Y junction",
    "Employee ID": "EMP_0034",
    "Employee Name": "Store_0008 Login",
    "Return Reason": "",
    "Item Code": "add81623-fd54-4655-ae05-6cedb2316f23",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "PERCENTAGE",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 1699,
    "Amount Paid": 1546,
    "Return Amount": 0,
    "Total Coupon Amount": 153,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 13,
    "_h": 20,
    "_m": 29
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0011_1726",
    "Order Type": "ONLINE",
    "Product Name": "Frido Premium Car Comfort Bundle",
    "Variant Name": "Midnight Black",
    "Size": "",
    "Customer Email": "9849093892@frido.in",
    "Customer Phone": "920000000000",
    "Customer Name": "rushender .",
    "New Customer": "No",
    "Heard About Frido": "YES",
    "Source": "GOOGLE_SEARCH",
    "Store Name": "Lakeshore Y junction",
    "Employee ID": "EMP_0034",
    "Employee Name": "Store_0008 Login",
    "Return Reason": "",
    "Item Code": "1ad66592-c10d-4573-a8dc-2c70fc2c1efb",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "PERCENTAGE",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 3999,
    "Amount Paid": 3639,
    "Return Amount": 0,
    "Total Coupon Amount": 360,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 18,
    "_h": 17,
    "_m": 46
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0011_1726",
    "Order Type": "ONLINE",
    "Product Name": "Frido Women's Arch Comfort Sandals",
    "Variant Name": "Light Gold / 6 UK (39 EU)",
    "Size": "6 UK (39 EU)",
    "Customer Email": "9849093892@frido.in",
    "Customer Phone": "920000000000",
    "Customer Name": "rushender .",
    "New Customer": "No",
    "Heard About Frido": "YES",
    "Source": "GOOGLE_SEARCH",
    "Store Name": "Lakeshore Y junction",
    "Employee ID": "EMP_0034",
    "Employee Name": "Store_0008 Login",
    "Return Reason": "",
    "Item Code": "fd578a0c-1e4c-4f21-8b11-7f2f550fa099",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "PERCENTAGE",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 2199,
    "Amount Paid": 2001,
    "Return Amount": 0,
    "Total Coupon Amount": 198,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 23,
    "_h": 12,
    "_m": 3
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0008_2136",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Women's Arch Comfort Sandals",
    "Variant Name": "Rose Gold / 5 UK (38 EU)",
    "Size": "5 UK (38 EU)",
    "Customer Email": "9890016222@frido.in",
    "Customer Phone": "920000000000",
    "Customer Name": "Ketan Bhatia",
    "New Customer": "Yes",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Kopa Mall",
    "Employee ID": "EMP_0028",
    "Employee Name": "shubham gupta",
    "Return Reason": "",
    "Item Code": "RTDMHN-2627N555653",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 2199,
    "Amount Paid": 2199,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 18,
    "_h": 19,
    "_m": 20
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0003_2527",
    "Order Type": "ONLINE",
    "Product Name": "Frido Adjustable Wedge Max Cushion",
    "Variant Name": "Sage Green",
    "Size": "",
    "Customer Email": "7617072452@frido.in",
    "Customer Phone": "918000000000",
    "Customer Name": "DHANANJAY JAISWAL",
    "New Customer": "No",
    "Heard About Frido": "YES",
    "Source": "INSTAGRAM",
    "Store Name": "Amar Tech Park",
    "Employee ID": "EMP_0010",
    "Employee Name": "Amar Tech Park",
    "Return Reason": "",
    "Item Code": "0bf04c7d-09b1-42bc-b241-bdcd2b61718d",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "PERCENTAGE",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 3699,
    "Amount Paid": 3514,
    "Return Amount": 0,
    "Total Coupon Amount": 185,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 1,
    "_h": 20,
    "_m": 37
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0005_4843",
    "Order Type": "ONLINE",
    "Product Name": "Frido Men's Cloud Comfort Sandal",
    "Variant Name": "Tan / 6 UK (40 EU)",
    "Size": "6 UK (40 EU)",
    "Customer Email": "anisharajbhar2126@gmail.com",
    "Customer Phone": "9130000000",
    "Customer Name": "Anisha Rajbhar",
    "New Customer": "No",
    "Heard About Frido": "NO",
    "Source": "",
    "Store Name": "Elpro PCMC",
    "Employee ID": "EMP_0014",
    "Employee Name": "Elpro PCMC",
    "Return Reason": "",
    "Item Code": "ea26859c-4d40-40dd-8041-1e466b06f0e2",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "PERCENTAGE",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 2399,
    "Amount Paid": 2279,
    "Return Amount": 0,
    "Total Coupon Amount": 120,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 0,
    "_h": 16,
    "_m": 54
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0010_3213",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Orthotics Knee Support Wrap",
    "Variant Name": "Black / M",
    "Size": "M",
    "Customer Email": "9702618404@frido.in",
    "Customer Phone": "920000000000",
    "Customer Name": "Anuj Rawal",
    "New Customer": "Yes",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "SkyCity Borivali",
    "Employee ID": "EMP_0035",
    "Employee Name": "Danish Bagavan",
    "Return Reason": "",
    "Item Code": "Rtdmhn-2627n281275",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 699,
    "Amount Paid": 699,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 1,
    "_h": 19,
    "_m": 11
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0003_2526",
    "Order Type": "ONLINE",
    "Product Name": "Frido Men's Comfort Dual Strap Sandals",
    "Variant Name": "Cloudy Grey / 11 UK (EUR 45)",
    "Size": "11 UK (EUR 45)",
    "Customer Email": "9420773273@frido.in",
    "Customer Phone": "919000000000",
    "Customer Name": "tejas gaikwad",
    "New Customer": "No",
    "Heard About Frido": "YES",
    "Source": "INSTAGRAM",
    "Store Name": "Amar Tech Park",
    "Employee ID": "EMP_0010",
    "Employee Name": "Amar Tech Park",
    "Return Reason": "",
    "Item Code": "eed0219a-04d4-4817-be27-4f4bc3b25fa5",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "PERCENTAGE",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 2499,
    "Amount Paid": 2374,
    "Return Amount": 0,
    "Total Coupon Amount": 125,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 3,
    "_h": 13,
    "_m": 28
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0013_1467",
    "Order Type": "ONLINE",
    "Product Name": "Frido Orthotics Knee Support Wrap",
    "Variant Name": "Black / XXL",
    "Size": "XXL",
    "Customer Email": "jeremiah.kollu@gmail.com",
    "Customer Phone": "8130000000",
    "Customer Name": "jeremiah kollu",
    "New Customer": "No",
    "Heard About Frido": "YES",
    "Source": "INSTAGRAM",
    "Store Name": "Frido Store Banjara Hills",
    "Employee ID": "EMP_0042",
    "Employee Name": "Frido Store Banjara Hills",
    "Return Reason": "",
    "Item Code": "a979419b-50e1-47f0-bb1d-2664c9f0fc05",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "FIXED",
    "Quantity": 2,
    "Returned Quantity": 0,
    "MRP": 699,
    "Amount Paid": 1094,
    "Return Amount": 0,
    "Total Coupon Amount": 105,
    "Combo Discount Amount": 199,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 0,
    "_h": 12,
    "_m": 45
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0013_1467",
    "Order Type": "ONLINE",
    "Product Name": "Frido Cloud Comfort Arch Support Slippers",
    "Variant Name": "Soft Peach / 7 UK",
    "Size": "7 UK",
    "Customer Email": "jeremiah.kollu@gmail.com",
    "Customer Phone": "8130000000",
    "Customer Name": "jeremiah kollu",
    "New Customer": "No",
    "Heard About Frido": "YES",
    "Source": "INSTAGRAM",
    "Store Name": "Frido Store Banjara Hills",
    "Employee ID": "EMP_0042",
    "Employee Name": "Frido Store Banjara Hills",
    "Return Reason": "",
    "Item Code": "53ed88ed-da07-4621-95ef-1395b4988e10",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "FIXED",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 949,
    "Amount Paid": 775,
    "Return Amount": 0,
    "Total Coupon Amount": 74,
    "Combo Discount Amount": 100,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 3,
    "_h": 13,
    "_m": 2
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0013_1467",
    "Order Type": "ONLINE",
    "Product Name": "Frido Women's Arch Comfort Sandals",
    "Variant Name": "Light Gold / 7 UK (40 EU)",
    "Size": "7 UK (40 EU)",
    "Customer Email": "jeremiah.kollu@gmail.com",
    "Customer Phone": "8130000000",
    "Customer Name": "jeremiah kollu",
    "New Customer": "No",
    "Heard About Frido": "YES",
    "Source": "INSTAGRAM",
    "Store Name": "Frido Store Banjara Hills",
    "Employee ID": "EMP_0042",
    "Employee Name": "Frido Store Banjara Hills",
    "Return Reason": "",
    "Item Code": "f470a22c-b8b1-4d26-9402-c5553a032c1c",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "FIXED",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 2199,
    "Amount Paid": 2006,
    "Return Amount": 0,
    "Total Coupon Amount": 193,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 20,
    "_h": 18,
    "_m": 19
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0013_1467",
    "Order Type": "ONLINE",
    "Product Name": "Frido Ultimate Pro Seat Cushion",
    "Variant Name": "Premium Grey",
    "Size": "",
    "Customer Email": "jeremiah.kollu@gmail.com",
    "Customer Phone": "8130000000",
    "Customer Name": "jeremiah kollu",
    "New Customer": "No",
    "Heard About Frido": "YES",
    "Source": "INSTAGRAM",
    "Store Name": "Frido Store Banjara Hills",
    "Employee ID": "EMP_0042",
    "Employee Name": "Frido Store Banjara Hills",
    "Return Reason": "",
    "Item Code": "a569c059-0f45-45ae-83ea-9a32ba378044",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "FIXED",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 1699,
    "Amount Paid": 1550,
    "Return Amount": 0,
    "Total Coupon Amount": 149,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 25,
    "_h": 19,
    "_m": 36
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0013_1467",
    "Order Type": "ONLINE",
    "Product Name": "Frido Cloud Comfort Arch Support Slippers",
    "Variant Name": "Cloud Grey / 6 UK",
    "Size": "6 UK",
    "Customer Email": "jeremiah.kollu@gmail.com",
    "Customer Phone": "8130000000",
    "Customer Name": "jeremiah kollu",
    "New Customer": "No",
    "Heard About Frido": "YES",
    "Source": "INSTAGRAM",
    "Store Name": "Frido Store Banjara Hills",
    "Employee ID": "EMP_0042",
    "Employee Name": "Frido Store Banjara Hills",
    "Return Reason": "",
    "Item Code": "377a5d13-e9a3-4bfd-afd6-446d675f3dcf",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "FIXED",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 949,
    "Amount Paid": 775,
    "Return Amount": 0,
    "Total Coupon Amount": 75,
    "Combo Discount Amount": 99,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 30,
    "_h": 14,
    "_m": 53
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0013_1467",
    "Order Type": "ONLINE",
    "Product Name": "FREE GIFT COUPON - â‚¹1000",
    "Variant Name": "Default Title",
    "Size": "",
    "Customer Email": "jeremiah.kollu@gmail.com",
    "Customer Phone": "8130000000",
    "Customer Name": "jeremiah kollu",
    "New Customer": "No",
    "Heard About Frido": "YES",
    "Source": "INSTAGRAM",
    "Store Name": "Frido Store Banjara Hills",
    "Employee ID": "EMP_0042",
    "Employee Name": "Frido Store Banjara Hills",
    "Return Reason": "",
    "Item Code": "4417fd2e-de7a-4171-a566-f2d2f035b00b",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "FIXED",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 0,
    "Amount Paid": 0,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 8,
    "_h": 20,
    "_m": 10
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0005_4842",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Men's Comfort Dual Strap Sandals",
    "Variant Name": "Classic Black / 9 UK (EUR 43)",
    "Size": "9 UK (EUR 43)",
    "Customer Email": "7821941980@frido.in",
    "Customer Phone": "7820000000",
    "Customer Name": "SAIJAD CHOUDHARY",
    "New Customer": "No",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Elpro PCMC",
    "Employee ID": "EMP_0014",
    "Employee Name": "Elpro PCMC",
    "Return Reason": "",
    "Item Code": "",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "PERCENTAGE",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 2499,
    "Amount Paid": 2374,
    "Return Amount": 0,
    "Total Coupon Amount": 125,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 4,
    "_h": 14,
    "_m": 27
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0001_2967",
    "Order Type": "ONLINE",
    "Product Name": "FREE GIFT COUPON - â‚¹1000",
    "Variant Name": "Default Title",
    "Size": "",
    "Customer Email": "hemantvanaju@gmail.com",
    "Customer Phone": "9420000000",
    "Customer Name": "hemant vanaju",
    "New Customer": "No",
    "Heard About Frido": "YES",
    "Source": "FRIENDS_FAMILY",
    "Store Name": "Phoenix Marketcity Vimannagar",
    "Employee ID": "EMP_0003",
    "Employee Name": "Phoenix Marketcity Vimannagar",
    "Return Reason": "",
    "Item Code": "5f5c80d5-ecfa-42ff-bd81-238527e5a91e",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "FIXED",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 0,
    "Amount Paid": 0,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 4,
    "_h": 13,
    "_m": 44
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0001_2967",
    "Order Type": "ONLINE",
    "Product Name": "Frido ErgoLuxe Executive Chair",
    "Variant Name": "Auburn",
    "Size": "",
    "Customer Email": "hemantvanaju@gmail.com",
    "Customer Phone": "9420000000",
    "Customer Name": "hemant vanaju",
    "New Customer": "No",
    "Heard About Frido": "YES",
    "Source": "FRIENDS_FAMILY",
    "Store Name": "Phoenix Marketcity Vimannagar",
    "Employee ID": "EMP_0003",
    "Employee Name": "Phoenix Marketcity Vimannagar",
    "Return Reason": "",
    "Item Code": "9fe3aa67-0647-407e-a29b-3049b3c7a1b9",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "FIXED",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 36999,
    "Amount Paid": 34499,
    "Return Amount": 0,
    "Total Coupon Amount": 2500,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 9,
    "_h": 19,
    "_m": 1
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0011_1725",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Active Knee Cap Support",
    "Variant Name": "M / Grey",
    "Size": "M",
    "Customer Email": "9440080160@frido.in",
    "Customer Phone": "919000000000",
    "Customer Name": "srinivas .",
    "New Customer": "Yes",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Lakeshore Y junction",
    "Employee ID": "EMP_0034",
    "Employee Name": "Store_0008 Login",
    "Return Reason": "",
    "Item Code": "RTDMHN-2627N248139",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "PERCENTAGE",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 899,
    "Amount Paid": 836,
    "Return Amount": 0,
    "Total Coupon Amount": 63,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 28,
    "_h": 18,
    "_m": 18
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0013_1466",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Ultimate Car Neck Rest Pillow",
    "Variant Name": "Premium Grey",
    "Size": "",
    "Customer Email": "9100044428@frido.in",
    "Customer Phone": "9100000000",
    "Customer Name": "DHIRAJ .",
    "New Customer": "No",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Frido Store Banjara Hills",
    "Employee ID": "EMP_0042",
    "Employee Name": "Frido Store Banjara Hills",
    "Return Reason": "",
    "Item Code": "RTD1572702",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 1099,
    "Amount Paid": 1099,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 13,
    "_h": 15,
    "_m": 35
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0017_1168",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Orthotics Heel Protector",
    "Variant Name": "Black / L",
    "Size": "L",
    "Customer Email": "bik32205@gmail.com",
    "Customer Phone": "7010000000",
    "Customer Name": "Bikram Singh",
    "New Customer": "No",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Vegas Mall",
    "Employee ID": "EMP_0062",
    "Employee Name": "Nishant Kumar",
    "Return Reason": "",
    "Item Code": "RTDMHN-2627N539473",
    "Payment Modes": "QR_PAYMENT",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 899,
    "Amount Paid": 899,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 7,
    "_h": 20,
    "_m": 52
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0013_1465",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Max Comfort Arch Cushion Insoles",
    "Variant Name": "Large (8-11 UK)",
    "Size": "Large (8-11 UK)",
    "Customer Email": "9100044428@frido.in",
    "Customer Phone": "919000000000",
    "Customer Name": "DHIRAJ .",
    "New Customer": "Yes",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Frido Store Banjara Hills",
    "Employee ID": "EMP_0042",
    "Employee Name": "Frido Store Banjara Hills",
    "Return Reason": "",
    "Item Code": "RTD1622466",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 599,
    "Amount Paid": 599,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 18,
    "_h": 11,
    "_m": 9
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0021_1012",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Cloud Seat Cushion",
    "Variant Name": "Pebble Grey",
    "Size": "",
    "Customer Email": "7070708851@frido.in",
    "Customer Phone": "917000000000",
    "Customer Name": "Deepak Yadav",
    "New Customer": "Yes",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Felix Plaza",
    "Employee ID": "EMP_0075",
    "Employee Name": "Ayushi .",
    "Return Reason": "",
    "Item Code": "RTDMHN-2627N457224",
    "Payment Modes": "CASH",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 1899,
    "Amount Paid": 1899,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 1,
    "_h": 14,
    "_m": 26
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0014_1261",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Ultimate Car Neck Rest Pillow",
    "Variant Name": "Premium Tan",
    "Size": "",
    "Customer Email": "bmskalal@gmail.com",
    "Customer Phone": "8500000000",
    "Customer Name": "SRINIVAS .",
    "New Customer": "No",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Kompally Store",
    "Employee ID": "EMP_0047",
    "Employee Name": "Kompally Store",
    "Return Reason": "",
    "Item Code": "196",
    "Payment Modes": "CASH",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 1099,
    "Amount Paid": 1099,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 26,
    "_h": 15,
    "_m": 43
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0019_1084",
    "Order Type": "OFFLINE",
    "Product Name": "Frido Crescent Adjustable Pillow",
    "Variant Name": "Default Title",
    "Size": "",
    "Customer Email": "9818107444@frido.in",
    "Customer Phone": "920000000000",
    "Customer Name": "ACTIVE PHYSIO HUB .",
    "New Customer": "Yes",
    "Heard About Frido": "",
    "Source": "",
    "Store Name": "Omaxe Store",
    "Employee ID": "EMP_0069",
    "Employee Name": "Hamid R",
    "Return Reason": "",
    "Item Code": "RTDMHN-2627N299493",
    "Payment Modes": "RAZORPAY",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 1499,
    "Amount Paid": 1499,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 4,
    "_h": 15,
    "_m": 0
  },
  {
    "POS Order ID": "INV_2627_FRIDO_0010_3212",
    "Order Type": "ONLINE",
    "Product Name": "3D Foot Scan",
    "Variant Name": "Default Title",
    "Size": "",
    "Customer Email": "9029008755@frido.in",
    "Customer Phone": "919000000000",
    "Customer Name": "vijay Shetty",
    "New Customer": "No",
    "Heard About Frido": "NO",
    "Source": "",
    "Store Name": "SkyCity Borivali",
    "Employee ID": "EMP_0035",
    "Employee Name": "Danish Bagavan",
    "Return Reason": "",
    "Item Code": "29fc6ca3-1e03-43c4-a4f2-7c80ab3b1e57",
    "Payment Modes": "RAZORPAY_POS",
    "Shopify Coupon Name": "",
    "Store Coupon Name": "",
    "Custom Coupon Name": "",
    "Quantity": 1,
    "Returned Quantity": 0,
    "MRP": 99,
    "Amount Paid": 99,
    "Return Amount": 0,
    "Total Coupon Amount": 0,
    "Combo Discount Amount": 0,
    "Price Adjustment Discount Amount": 0,
    "Freebie Discount Amount": 0,
    "_d": 2,
    "_h": 16,
    "_m": 17
  }
] as const;
